title: "Lening Li"
tagline: "A jekyll theme that looks like a shell/terminal"
description: "This is the personal website for Lening Li."
github_username: leelening
baseurl: ""
url: "https://leelening.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - publications.md
  - projects.md
  - posts.md
  - contact.md

collections:
  projects:
    output: true

# set the size of the text to 'large' or 'small', default is small
font-size: small

remote_theme: "tareqdandachi/jekyll-shell-theme"
