title: "Lening Li"
tagline: "A jekyll theme that looks like a shell/terminal"
description: "This is the personal website for Lening Li."
github_username: leelening
twitter_username: LeeLening
baseurl: ""
url: "https://leelening.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll/scholar

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - publications.md
  - research.md
  # - software.md
  # - posts.md
  - travel.md
  - contact.md

collections:
  research:
    output: true

include:
  - _data

# set the size of the text to 'large' or 'small', default is small
font-size: small

remote_theme: "tareqdandachi/jekyll-shell-theme"

scholar:
  style: apa
  locale: en

  sort_by: year, month
  order: descending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"